// components/manage/Clusteradd.tsx
"use client";
import React, { useState } from "react";
import Table from "../table/Table"; // Adjust path as necessary
import { clusterdata, OpeningBalance } from "../type";
import { formatDate } from "@/lib/utils";
import { Button } from "react-bootstrap";
import { KTIcon } from "@/_metronic/helpers";
import CustomModal from "@/common/CustomModal";
import { toast } from "react-toastify";

type Props = {
    initialOpenBalanceData: OpeningBalance[];
};

const Openingbalanceadd = ({ initialOpenBalanceData }: Props) => {
  const [showPrintModal, setShowPrintModal] = useState(false);
  const [clusterName, setClusterName] = useState("");
  const [error, setError] = useState<string>("");
  const [updateClusterId, setUpdateClusterId] = useState<number | null>(null);
  const [clusterData, setClusterData] = useState<OpeningBalance[]>(initialOpenBalanceData); // State for cluster data

  const data = clusterData.map((cluster) => ({
    cluster_id: cluster.open_bal_id,
    cluster_name: cluster.open_bal,
    status: cluster.status,
    ins_date_time:
      typeof cluster.ins_date_time === "string"
        ? formatDate(cluster.ins_date_time)
        : formatDate(cluster.ins_date_time.toISOString()),
  }));

  const columns = [
    {
      accessorKey: "cluster_id",
      header: "ID",
    },
    {
      accessorKey: "cluster_name",
      header: "Cluster Name",
    },
    {
      accessorKey: "status",
      header: "Status",
    },
    {
      accessorKey: "ins_date_time",
      header: "Add Time",
    },
    {
      accessorKey: "actions",
      header: "Actions",
      cell: ({ row }: any) => (
        <div>
          <button className="btn btn-sm btn-primary" onClick={() => handleEdit(row.original)}>Edit</button>
          <button
            className={`btn btn-sm ${row.original.status === "Active" ? "btn-danger" : "btn-warning"} ms-5`}
            onClick={() => handleDeactivate(row.original.cluster_id, row.original.status)}
          >
            {row.original.status === "Active" ? "Deactivate" : "Activate"}
          </button>
        </div>
      ),
    },
  ];

  const handleDeactivate = async (clusterId: any, currentStatus: any) => {
    const confirmMessage = currentStatus === "Active"
      ? "Are you sure you want to deactivate this cluster?"
      : "Are you sure you want to activate this cluster?";

    if (window.confirm(confirmMessage)) {
      try {
        const response = await fetch(`/api/clustersapi/clusters/${clusterId}`, {
          method: "PATCH",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            status: currentStatus === "Active" ? "Deactive" : "Active",
          }),
        });

        if (response.ok) {
          // Update local state without page reload
          setClusterData(prevData => 
            prevData.map(cluster => 
              cluster.open_bal_id === clusterId 
                ? { ...cluster, status: currentStatus === "Active" ? "Deactive" : "Active" }
                : cluster
            )
          );
          toast.success(`Cluster ${currentStatus === "Active" ? "deactivated" : "activated"} successfully!`);
        } else {
          toast.error("Failed to change the cluster status.");
        }
      } catch (error) {
        console.error("Error changing the cluster status:", error);
        toast.error("An unexpected error occurred.");
      }
    }
  };

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();

    if (!clusterName) {
      setError("Cluster name is required.");
      return;
    }

    try {
      const method = updateClusterId ? "PUT" : "POST"; 
      const url = updateClusterId
        ? `/api/clustersapi/update/updateCluster`
        : `/api/clustersapi/insert/clusters`;

      const response = await fetch(url, {
        method,
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          cluster_name: clusterName,
          // Do not include 'cluster_id' for new inserts
          ...(updateClusterId && { cluster_id: updateClusterId }),
        }),
      });

      if (response.ok) {
        // Update local state without page reload
        if (updateClusterId) {
          setClusterData(prevData =>
            prevData.map(cluster =>
              cluster.open_bal_id === updateClusterId
                ? { ...cluster, cluster_name: clusterName }
                : cluster
            )
          );
          toast.success("Cluster updated successfully!");
        } else {
          // New Cluster object without ID since it's auto-incremented
          const newCluster = { 
            // Do not set 'cluster_id', it will be generated by the database
            cluster_name: clusterName,
            status: 'Active', // Default status
            ins_date_time: new Date().toISOString(), // Current time as insert date
          };
          
          // Assuming your API returns the newly created object with ID after creation.
          const createdResponse = await fetch(`/api/clustersapi/insert/clusters`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(newCluster),
          });
          
          if (createdResponse.ok) {
            const createdData = await createdResponse.json();
            setClusterData(prevData => [...prevData, createdData]); // Add created data to state
            toast.success("Cluster inserted successfully!");
          } else {
            toast.error("Failed to insert new cluster.");
          }
        }
        
        handleClosePrint();
      } else {
        toast.error(`Failed to ${updateClusterId ? "update" : "insert"} cluster.`);
      }
    } catch (error) {
      console.error("Error during operation:", error);
      toast.error("An unexpected error occurred.");
    }
  };

  const handleEdit = (cluster: any) => {
    setUpdateClusterId(cluster.cluster_id); // Set ID for updating
    setClusterName(cluster.cluster_name); // Set current name for editing
    handleShowPrint(); // Open modal for editing
  };

  const handleShowPrint = () => setShowPrintModal(true);
  
  const handleClosePrint = () => {
    setShowPrintModal(false);
    setClusterName("");
    setError("");
    setUpdateClusterId(null); // Reset update ID when closing
  };

  return (
    <div>
      <Table
        data={data}
        columns={columns}
        Button={
          <Button
            variant="primary"
            onClick={handleShowPrint}
            className="btn"
            style={{ minWidth: "120px" }}
          >
            <KTIcon iconName={"printer"} className="fs-3" iconType="solid" />
            Add Cluster
          </Button>
        }
      />

      <CustomModal
        show={showPrintModal}
        handleClose={handleClosePrint}
        handleSubmit={handleSubmit}
        title={updateClusterId ? "Update Cluster Name" : "Insert Cluster Name"}
        formData={{
          fields: [
            {
              label: "Enter Cluster Name:",
              value: clusterName,
              type:"text",
              placeholder: "Enter Cluster name",
              error,
              onChange: (e) => setClusterName(e.target.value),
            },
          ],
          error,
        }}
        submitButtonLabel="Submit"
      />
      
    </div>
  );
};

export default Openingbalanceadd;